import random

zoolist = [
"https://en.wikipedia.org/wiki/African_scops_owl",
"https://en.wikipedia.org/wiki/Anotopterus",
"https://www.allaboutbirds.org/guide/Arctic_Tern/overview",
"https://en.wikipedia.org/wiki/Asian_giant_softshell_turtle",
"https://en.wikipedia.org/wiki/Atheris",
"https://en.wikipedia.org/wiki/Atretochoana",
"https://en.wikipedia.org/wiki/Attacus_atlas",
"https://en.wikipedia.org/wiki/Aye-aye",
"https://en.wikipedia.org/wiki/Babirusa",
"https://en.wikipedia.org/wiki/Blue-footed_booby",
"https://en.wikipedia.org/wiki/Braconidae",
"https://en.wikipedia.org/wiki/Cordylobia_anthropophaga",
"https://en.wikipedia.org/wiki/Euspinolia_militaris",
"https://en.wikipedia.org/wiki/Frilled_shark",
"https://en.wikipedia.org/wiki/Giant_golden-crowned_flying_fox",
"https://en.wikipedia.org/wiki/Glaucus_atlanticus",
"https://en.wikipedia.org/wiki/Goliath_birdeater",
"https://en.wikipedia.org/wiki/Grimpoteuthis",
"https://en.wikipedia.org/wiki/Honeypot_ant",
"https://en.wikipedia.org/wiki/Hummingbird_hawk-moth",
"https://en.wikipedia.org/wiki/Indian_chameleon",
"https://en.wikipedia.org/wiki/Jabiru",
"https://en.wikipedia.org/wiki/Japanese_sawshark",
"https://www.desertusa.com/animals/jerboa.html",
"https://en.wikipedia.org/wiki/Kitti%27s_hog-nosed_bat",
"https://en.wikipedia.org/wiki/Kiwa_hirsuta",
"https://en.wikipedia.org/wiki/Lasiognathus_amphirhamphus",
"https://en.wikipedia.org/wiki/Leafy_seadragon",
"https://en.wikipedia.org/wiki/Lowland_streaked_tenrec",
"https://en.wikipedia.org/wiki/Manduca_quinquemaculata",
"https://www.peacockspider.org/",
"https://en.wikipedia.org/wiki/Philippine_eagle",
"https://en.wikipedia.org/wiki/Pink_fairy_armadillo",
"https://en.wikipedia.org/wiki/Prickly_anglerfish",
"https://en.wikipedia.org/wiki/Purple_frog",
"https://en.wikipedia.org/wiki/Rainbow_lorikeet",
"https://en.wikipedia.org/wiki/Red_lionfish",
"https://en.wikipedia.org/wiki/Red-lipped_batfish",
"https://en.wikipedia.org/wiki/Rhinochimaera",
"https://en.wikipedia.org/wiki/Sand_devil",
"https://en.wikipedia.org/wiki/Scotoplanes",
"https://en.wikipedia.org/wiki/Sunda_flying_lemur",
"https://en.wikipedia.org/wiki/Synchiropus_splendidus",
"https://en.wikipedia.org/wiki/Telmatobius_culeus",
"https://en.wikipedia.org/wiki/Thorny_devil",
"https://en.wikipedia.org/wiki/Weaver_ant",
"https://en.wikipedia.org/wiki/White-bellied_go-away-bird"]

def zooo():
    return(random.choice(zoolist))



